### ISSUE TITLE
Moon is not centered under the switch

### ISSUE THREAD

**Issue by ashirviskas** [domnantas/lunar-dark-mode-switch#1]
/r/mildlyinfuriating
![image](https://user-images.githubusercontent.com/11985242/157747533-dc7adf4e-38ef-41be-8e8e-2167241e3afe.png)

Otherwise, great project, I use it to track my moon phases :+1:

**Comment by domnantas** [comment]
Hey! Thanks for the report, apparently emojis render very differently on different devices. Even Mac and iOS don't render them consistently.

Fixed the issue by using open source Twitter emoji everywhere. Also replaced the white switch with an Earth emoji.

And this gave me another idea 😄 There are 3 Earth emojis 🌍🌎🌏. We should display the earth location at which currently it is daytime

**Comment by domnantas** [comment]
Ok lol implemented different earth emojis according to daylight

**Comment by ashirviskas** [comment]
The new version looks great and very satisfying, thanks for amazing support!
